version: 2.1

jobs:
  build-learning-nodejs:
    working_directory: ~/learning-nodejs
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-nodejs-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: learning-nodejs-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  learning-nodejs-workflow:
    jobs:
      - build-learning-nodejs
